### ISSUE TITLE
Speed of async mode

### ISSUE THREAD

**Issue by karantin2020** [OpenSystemsLab/rethinkdb.nim#4]
Hello I tested code bellow with threads=off and on (+ async features)

```nim
proc main() =
  var r = newRethinkclient()
  r.connect()
  r.repl()
  for _ in 0..<1_000:
    discard r.table("tv_shows").run()
  r.close()

main()
```

This sync mode of rethink client is faster that async one for about 38-40%.

Did you test library's speed?

**Comment by rgv151** [comment]
I didn't do benchmarking for this project yet, I will create some more test scripts when I have spare time

**Comment by rgv151** [comment]
hmm, after some tests, async mode is pretty much faster than sync. there is not much diffirent btw sync and async if you using `waitFor`, cuz they are both io-blocking
