### ISSUE TITLE
Run/Query not Spawn/GC Safe

### ISSUE THREAD

**Issue by stelford** [OpenSystemsLab/rethinkdb.nim#6]
assuming I have code like the following inside a spawned function;  

let r = newRethinkClient(address = "10.0.10.115", port = Port(28015), auth = "", db = "fudge")
r.connect()
r.repl()
var ret = r.table("user").get("043ef2b9-512e-41fb-9c1b-2577bc6563ba").run()

when compiling, with --threads:on, I get; 

test_service.nim(123, 33) Error: 'spawn' takes a GC safe call expression

I suspect the problem lies inside private/types.nim around the declaration
`
RqlQuery* = ref object of RootObj
`
but more than that, I can't say (still relatively new to nim)

**Comment by rgv151** [comment]
can you run tests/test_threaded.nim with `--theads:on`

**Comment by stelford** [comment]
Hey, that runs to completion without any errors

**Comment by stelford** [comment]
Does the code inside the test/test_threaded actually 'do' inserts ?! Reason I ask, if I do 
  #discard r.db("test").table("test").insert(&*{"c": c}).run(r, noreply=true, durability="soft")
  discard r.db("test").table("test").insert(&*{"c": c}).run(r)
Then it complains about missing table Test.test, but with the noreply and durability soft, it doesn't even appear to hit the db as there is no error

**Comment by stelford** [comment]
Rolling back the PR I issued (after creating Test.test) and running the test/test_threaded.nim gives me;

/home/ubuntu/stef/rethinkdb.nim/private/connection.nim(266, 8) Warning: 'continueQuery' is not GC-safe as it calls 'runQuery' [GcUnsafe2]
/home/ubuntu/stef/rethinkdb.nim/private/rql.nim(119, 9) Warning: 'run' is not GC-safe as it calls 'continueQuery' [GcUnsafe2]
test_threaded.nim(10, 6) Error: 'insert' is not GC-safe as it calls 'run'

**Comment by rgv151** [comment]
you must create `test` table first. when `noreply` option set to `true`, server will returns nothing (just use it for batching purpose)

**Comment by stelford** [comment]
yup, I did that step before I rolled back my PR .. problem exists as above sadly.

**Comment by rgv151** [comment]
so they are gone w/ your changes?

**Comment by stelford** [comment]
they are gone with those changes, yes. I do think that it's the 'tip of the iceberg' though, as I suspect other methods are not thread/gc-safe but, at least if anyone is blocked, they can look at the changeset/PR and figure it out

**Comment by rgv151** [comment]
merged, thank you!
